In [45]:
import numpy as np
import pandas as pd
import plotly.express as px 
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection  import train_test_split
from sklearn.linear_model import LinearRegression

from sklearn.metrics import r2_score , mean_squared_error

In [46]:
df = pd.read_csv('house_prices_practice.csv')

In [47]:
df.head(5)

,Id,OverallQual,GrLivArea,GarageCars,TotalBsmtSF,YearBuilt,FullBath,BedroomAbvGr,LotArea,SalePrice
0,1,7,1560,0,1658,1969,2,1,8059,177106
1,2,4,2827,2,1319,2012,3,4,13530,301044
2,3,8,3920,0,841,2010,1,4,9010,360609
3,4,5,3044,0,1058,1998,0,4,13207,240556
4,5,7,801,1,2428,2020,0,1,9117,193656

In [48]:
df['FullBath'].unique().sum()

np.int64(6)

In [49]:
df.isnull().sum()

Id              0
OverallQual     0
GrLivArea       0
GarageCars      0
TotalBsmtSF     0
YearBuilt       0
FullBath        0
BedroomAbvGr    0
LotArea         0
SalePrice       0
dtype: int64

In [50]:
df.drop(columns=['Id'] , axis=1 , inplace=True)

In [51]:
x = df.drop('SalePrice', axis=1)
y = df['SalePrice']

In [52]:
y

0      177106
1      301044
2      360609
3      240556
4      193656
        ...
295    250604
296    329906
297    184623
298    303345
299    204982
Name: SalePrice, Length: 300, dtype: int64

In [53]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y ,test_size= 0.2,random_state=42 )

In [54]:
from sklearn.preprocessing import PolynomialFeatures

In [55]:
df.head(5)

,OverallQual,GrLivArea,GarageCars,TotalBsmtSF,YearBuilt,FullBath,BedroomAbvGr,LotArea,SalePrice
0,7,1560,0,1658,1969,2,1,8059,177106
1,4,2827,2,1319,2012,3,4,13530,301044
2,8,3920,0,841,2010,1,4,9010,360609
3,5,3044,0,1058,1998,0,4,13207,240556
4,7,801,1,2428,2020,0,1,9117,193656

In [56]:
poly = PolynomialFeatures(degree=3)
x_poly_train = poly.fit_transform(x_train)
x_poly_test = poly.transform(x_test)

In [57]:
poly_model = LinearRegression()
poly_model.fit(x_poly_train , y_train)

LinearRegression()

In [58]:
y_poly_pred_trainn = poly_model.predict(x_poly_train)
y_poly_pred_test = poly_model.predict(x_poly_test)

In [59]:
mes = mean_squared_error(y_test ,y_poly_pred_test)
r2 = r2_score(y_test ,y_poly_pred_test)
mes , r2

(208066866.82772678, 0.9633283715351912)

In [1]:
pip install tkintertable

Collecting tkintertable
  Downloading tkintertable-1.3.3.tar.gz (58 kB)
     ---------------------------------------- 0.0/58.7 kB ? eta -:--:--
     ------ --------------------------------- 10.2/58.7 kB ? eta -:--:--
     ------------------- ------------------ 30.7/58.7 kB 262.6 kB/s eta 0:00:01
     -------------------------------------- 58.7/58.7 kB 343.9 kB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting future (from tkintertable)
  Using cached future-1.0.0-py3-none-any.whl.metadata (4.0 kB)
Using cached future-1.0.0-py3-none-any.whl (491 kB)
Building wheels for collected packages: tkintertable
  Building wheel for tkintertable (pyproject.toml): started
  Building wheel for tkintertable (pyproject.toml): finished with status 'done'
  Created wheel for tkintertable: filename=tkintertable-1.3.3-py3-none-any.whl size=66249 sha256=ab84720c35f9b714f1ccc8d4d5e0981e2c43c6403a4054b6bb2496b2cf33f4fc
  Stored in directory: c:\users\almnara\appdata\local\pip\cache\wheels\d3\2b\b5\2874f754ec8756ccf42e1a87e5b4019c24c2699220ee60adef
Successfully built tkintertable
Installing collected packages: future, tkintertable
Successfully installed future-1.0.0 tkintertable-1.3.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip