In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer

In [2]:
data = load_breast_cancer()

In [3]:
df =pd.DataFrame(data=data['data'],columns=data.feature_names)

In [4]:
df.head(5)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [5]:
df['target'] = data['target']
df.head(5)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [6]:
df['target'].value_counts()

target
1    357
0    212
Name: count, dtype: int64

In [7]:
x = df.iloc[:,:-1].values 
y = df['target'].values

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [9]:
def sigmoid (x) :
    return 1/(1+np.exp(-x))

In [10]:
def  update_weighs(weights , x , z ,y , lr) :
    m = len(y)
    dw = (1/m) *  np.dot(x.T,(z-y))
    weights = weights - lr*dw
    return weights

In [11]:
def  update_baiss(baiss , x , z ,y , lr) :
    m = len(y)
    db = (1/m) *  np.sum(z-y)
    baiss = baiss - lr*db
    return baiss

In [12]:
def perceptron(x,weights , baiss) : 
    z = np.dot(x, weights ) + baiss
    y_pred = sigmoid(z)
    y_p = [1 if y>0.5 else 0 for y in y_pred]
    return y_p

In [13]:
def accuracy(y_pred , y_actual) :
    return np.sum(y_pred == y_actual)/len(y_actual)

In [28]:
lr =0.001 
weights = np.zeros(x_train.shape[1])
bais = 0
for i in range(20000):
 pred = perceptron(x_train, weights, bais)
 weights = update_weighs(weights, x_train, pred, y_train, lr)
 bais = update_baiss(bais, x_train, pred, y_train, lr)

C:\Users\almnara\AppData\Local\Temp\ipykernel_22168\2931602468.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))

In [29]:
y_pred = perceptron(x_train, weights, bais)
print("Accuracy", accuracy(y_pred, y_train))

Accuracy 0.8725274725274725

C:\Users\almnara\AppData\Local\Temp\ipykernel_22168\2931602468.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))

In [30]:
y_pred = perceptron(x_test, weights, bais)

C:\Users\almnara\AppData\Local\Temp\ipykernel_22168\2931602468.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))

In [31]:
print("Accuracy", accuracy(y_pred, y_test))

Accuracy 0.8859649122807017